// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0bTErSVdrByuBFDT8c1rx92e0vXoYIdU',
    appId: '1:1003760863678:web:19b452b4e6ff4bf46311ef',
    messagingSenderId: '1003760863678',
    projectId: 'ase-rag-status',
    authDomain: 'ase-rag-status.firebaseapp.com',
    storageBucket: 'ase-rag-status.firebasestorage.app',
    measurementId: 'G-LCWLC5QFLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMCAOv9NSeUxHgsXOhzNF1F20G-PQ9PeI',
    appId: '1:1003760863678:android:8fda1f307ec8824a6311ef',
    messagingSenderId: '1003760863678',
    projectId: 'ase-rag-status',
    storageBucket: 'ase-rag-status.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCimdTIQy21rYScVxWW9vYdbOmxsNAmXWw',
    appId: '1:1003760863678:ios:2e3de5699e7458b96311ef',
    messagingSenderId: '1003760863678',
    projectId: 'ase-rag-status',
    storageBucket: 'ase-rag-status.firebasestorage.app',
    iosBundleId: 'com.example.aseRag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCimdTIQy21rYScVxWW9vYdbOmxsNAmXWw',
    appId: '1:1003760863678:ios:2e3de5699e7458b96311ef',
    messagingSenderId: '1003760863678',
    projectId: 'ase-rag-status',
    storageBucket: 'ase-rag-status.firebasestorage.app',
    iosBundleId: 'com.example.aseRag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0bTErSVdrByuBFDT8c1rx92e0vXoYIdU',
    appId: '1:1003760863678:web:ebd43f33601c51536311ef',
    messagingSenderId: '1003760863678',
    projectId: 'ase-rag-status',
    authDomain: 'ase-rag-status.firebaseapp.com',
    storageBucket: 'ase-rag-status.firebasestorage.app',
    measurementId: 'G-VY9QW3ERPS',
  );
}
